[package]
name = "lzstd"
version = "0.0.1"
authors = ["semiviral"]
edition = "2021"

[dependencies.spin]
git = "https://github.com/linuiz-project/spin-rs"
[dependencies]
bit_field = "*"
bitflags = "*"
paste = "*"