[package]
name = "libcommon"
version = "0.0.1"
authors = ["semiviral"]
edition = "2021"

[dependencies.spin]
git = "https://github.com/linuiz-project/spin-rs"
spin = { git = "../spin-rs/" }
bit_field = "*"
bitflags = "*"
paste = "*"